### ISSUE TITLE
Argument of type '{ entryId: any; fieldId: string; }' is not assignable to parameter of type '{ fieldId: string; } & { locale?: string; }'.   Object literal may only specify known properties, and 'entryId' does not exist in type '{ fieldId: string; } & { locale?: string; }'.

### ISSUE THREAD

**Issue by j-quelly** [contentful/live-preview#182] opened 2023-06-27 17:54 UTC
Argument of type '{ entryId: any; fieldId: string; }' is not assignable to parameter of type '{ fieldId: string; } & { locale?: string; }'.
  Object literal may only specify known properties, and 'entryId' does not exist in type '{ fieldId: string; } & { locale?: string; }'.
  
  In the documentation is says that the following is valid:
  
```
    [BLOCKS.HEADING_1]: (node, children) => {
      const { fieldId } = h1;
      return (
        <Typography
          {...h1}
          {...inspectorProps({
            entryId: sys.id, // <------------ Typescript does not like this
            fieldId,
          })}
        >
          {children}
        </Typography>
      );
    },
```

Can we patch this or will we have to create a new instance of inspector props for each unique id like so:

```
const element1 = useContentfulInspectorMode({ entryId: 'foo' });
const element2 = useContentfulInspectorMode({ entryId: 'bar' });
const element3 = useContentfulInspectorMode({ entryId: 'baz' });
```

**Comment by chrishelgert** [comment] 2023-06-28 07:17
Hey,
thanks for reporting the issue, how are you calling the `useContentfulInspectorMode` initially?
I tried it out and it should work out if you don't provide a property to the `useContentfulInspectorMode`

```
const Demo = () => {
  const inspectorMode = useContentfulInspectorMode()

  return (
    <div {...inspectorMode({ entryId: '1', fieldId:'test' })}>
      <h1 {...inspectorMode({ entryId: '2', fieldId:'headline' })}>Test</h1>
    </div>
  )
}
```

**Comment by j-quelly** [comment] 2023-06-28 19:55
@chrishelgert here is the full code:

```
const Headings = ({ h1, h2, h3, h4, h5, h6 }: IHeadings, sys) => {
  const inspectorProps = useContentfulInspectorMode();
  return {
    [BLOCKS.HEADING_1]: (node, children) => {
      const { fieldId } = h1;
      return (
        <Typography
          {...h1}
          {...inspectorProps({
            entryId: sys.id,
            fieldId,
          })}
        >
          {children}
        </Typography>
      );
    },
    [BLOCKS.HEADING_2]: (node, children) => {
      const { fieldId } = h2;
      return (
        <Typography
          {...h2}
          {...inspectorProps({
            entryId: sys.id,
            fieldId,
          })}
        >
          {children}
        </Typography>
      );
    },
    [BLOCKS.HEADING_3]: (node, children) => {
      const { fieldId } = h3;
      return (
        <Typography
          {...h3}
          {...inspectorProps({
            entryId: sys.id,
            fieldId,
          })}
        >
          {children}
        </Typography>
      );
    },
    [BLOCKS.HEADING_4]: (node, children) => {
      return <Typography {...h4}>{children}</Typography>;
    },
    [BLOCKS.HEADING_5]: (node, children) => {
      return <Typography {...h5}>{children}</Typography>;
    },
    [BLOCKS.HEADING_6]: (node, children) => {
      return <Typography {...h6}>{children}</Typography>;
    },
  };
};
```

**Comment by j-quelly** [comment] 2023-07-28 18:05
@chrishelgert any updates here?

**Comment by j-quelly** [comment] 2023-08-01 02:13
<img width="671" alt="Screenshot 2023-07-31 at 7 12 34 PM" src="https://github.com/contentful/live-preview/assets/10458851/5d995483-d5c3-48ce-99cb-a1f47217ec65">
<img width="671" alt="Screenshot 2023-07-31 at 7 12 34 PM" src="https://github.com/contentful/live-preview/assets/10458851/79f692a9-178e-4635-b310-4ffab1f8face">
<img width="396" alt="Screenshot 2023-07-31 at 7 13 37 PM" src="https://github.com/contentful/live-preview/assets/10458851/3aef318b-7056-4522-882e-48b17ee361c1">

Problem persists even after upgrading

**Comment by chrishelgert** [comment] 2023-08-01 08:20
Hey 👋 ,
What `typescript` version are you using?
I build a quick demo with `"typescript": "^5.0.2"` and the latest live preview version, and there would be no warning

![Screenshot 2023-08-01 at 10 18 18](https://github.com/contentful/live-preview/assets/3918488/e4ec1a17-0a9a-48f7-b9e1-4c0831dc0e66)

**Comment by j-quelly** [comment] 2023-08-01 21:09
@chrishelgert I upgraded to the same version as you and still have the error:

![Screenshot 2023-08-01 at 2 09 16 PM](https://github.com/contentful/live-preview/assets/10458851/a8140e9e-71a0-4cce-bd05-2ca63aa11021)

**Comment by j-quelly** [comment] 2023-08-03 16:49
This is still an issue, but I've worked around this by doing the following:

```
  const inspectorPropsH1 = useContentfulInspectorMode({ entryId: sys?.id });
  const inspectorPropsH2 = useContentfulInspectorMode({ entryId: sys?.id });
  const inspectorPropsH3 = useContentfulInspectorMode({ entryId: sys?.id });
  
  // all other code omitted
  
      [BLOCKS.HEADING_1]: (node, children) => {
      return (
        <Typography
          {...h1}
          {...inspectorPropsH1({
            fieldId: h1?.fieldId,
            // no more TS error
          })}
        >
```

**Comment by YvesRijckaert** [comment] 2023-08-14 08:55
Closing since we can't reproduce and there seems to be a workaround in place.

**Closed by YvesRijckaert** 2023-08-14 08:55 UTC
